security:
    enable_authenticator_manager: true
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
        # used to reload user from session & other features (e.g. switch_user)
    firewalls:
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticators: 
                - 'App\Security\FormLoginAuthenticator'
            logout:
                path: app_logout
                target: app_homepage

    access_control:
        - { path: '^/admin', roles: ROLE_ADMIN }
        - { path: '^/login', roles: PUBLIC_ACCESS }
        - { path: '^/', roles: PUBLIC_ACCESS }