security:
    password_hashers:
        App\Entity\User:
            algorithm: auto
    providers:
        in_memory:
            memory:
                users:    
                    admin:
                        password: '$2y$13$DvTDfuX3YiIR4FLKja.EF.mbA8VqH7GH7l91G8E1wG0PjzzAY/iCC'
                        roles: ['ROLE_ADMIN']

    firewalls:
        secured_area:
        anonymous: ~
        http_basic: ~
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
