controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
accueil:
    path: /
    controller: App\Controller\FirstController::index
mentions:
    path: /mentions
    controller: App\Controller\MentionsLegalesController::index
